name: seg-tool
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - libcxx=14.0.6
  - libffi=3.4.2
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.8.16
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.41.1
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - black==23.3.0
    - click==8.1.3
    - coloredlogs==15.0.1
    - contourpy==1.0.7
    - cycler==0.11.0
    - distinctipy==1.2.2
    - flatbuffers==23.3.3
    - fonttools==4.39.3
    - humanfriendly==10.0
    - imageio==2.27.0
    - importlib-resources==5.12.0
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - mypy-extensions==1.0.0
    - networkx==3.1
    - numpy==1.24.2
    - onnxruntime==1.14.1
    - opencv-python==4.7.0.72
    - packaging==23.0
    - pathspec==0.11.1
    - pillow==9.5.0
    - platformdirs==3.2.0
    - protobuf==4.22.1
    - pycocotools==2.0.6
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pywavelets==1.4.1
    - scikit-image==0.20.0
    - scipy==1.9.1
    - simplification==0.6.7
    - six==1.16.0
    - sympy==1.11.1
    - tifffile==2023.3.21
    - tomli==2.0.1
    - typing-extensions==4.5.0
    - zipp==3.15.0
prefix: /Users/athena/opt/anaconda3/envs/seg-tool
